name: Build-dist

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.spec'
      - 'requirements.txt'
      - 'VERSION'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.spec'
      - 'requirements.txt'
      - 'VERSION'

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "version=$(<VERSION)" >> $GITHUB_OUTPUT

  build:
    runs-on: ${{ matrix.os }}-latest
    needs: get-version
    strategy:
      matrix:
        os: [ macos, windows ]

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Windows dependency
        if: matrix.os == 'windows'
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt -PathType leaf) {
            pip install -r requirements.txt
          }
          pip install pyinstaller

      - name: Mac dependency
        if: matrix.os == 'macos'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
              pip install -r requirements.txt
          fi
          pip install pyinstaller

      - name: Run tests
        run: |
          pip install pytest
          python -m pytest tests/ -v

      - name: Windows Build
        if: matrix.os == 'windows'
        env:
          APP_VERSION: ${{ needs.get-version.outputs.version }}
        run: |
          pyinstaller -y ssa_hdrify_windows.spec

      - name: Mac Build
        if: matrix.os == 'macos'
        env:
          APP_VERSION: ${{ needs.get-version.outputs.version }}
        run: |
          pyinstaller -y ssa_hdrify_macos.spec

      - name: Mac clean up dist folder
        if: matrix.os == 'macos'
        run: rm -rf dist/ssa_hdrify

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssa-hdrify-${{ matrix.os }}-${{ needs.get-version.outputs.version }}
          path: dist
